eduapp/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'edu-app'
from . import views

urlpatterns = [
    path('main/', views.MainPage.as_view(), name='MainPage'),
    path('search', views.Search.as_view(),name="SearchPage"),
    # path('signup/', views.RegistrationView.as_view(), name='SignUp'),
    path('', views.LoginView.as_view(), name='SignIn'),
    path('logout/', LogoutView.as_view(next_page="/"), name='LogOut'),
    # path('createcourse/', views.CreateCourse.as_view(), name='CreateCourse'),
    # path('course-list/', views.TeachersCourse.as_view(), name='TeachersCourse'),
    path('learn-course-list/', views.StudentsCourse.as_view(), name='StudentsCourse'),
    # path('course-list/<int:pk>/', views.TeachersCourseDetail.as_view(), name='TeachersCourseDetail'),
    # path('course/<pk>/update', views.CourseContentUpdate.as_view(), name="ContentUpdate"), 
    # path('course/<pk>/delete/', views.CourseContentDelete.as_view(), name="ContentDelete"),
    path('course/<int:pk>/', views.CourseDetail.as_view(), name="CourseDetail"),
    # path('course/<int:course>/content/<int:content>', views.CourseDetailContent.as_view(), name="CourseDetailContent"),

    path('detail-course/<int:pk>/', views.StudentCourseDetail.as_view(), name='CourseShow'),
    path('learn-detail-course/<int:pk>/', views.LearnStudentCourseDetail.as_view(), name='LearnCourseShow'),

    path('add-course/<int:pk>/', views.AddCourseToLearn.as_view(), name='CourseAdd'),
    path('category/<int:pk>/', views.CourseByCategory.as_view(), name='CourseByCategory'),
    # path('create-test/<int:pk>/', views.CreateTest.as_view(), name='CreateTest'),
    # path('control-test/<int:pk>/', views.TeacherTestDetail.as_view(), name='ControlTest'),
    # path('past-test/<int:pk>/', views.StudentTestDetail.as_view(), name='PastTest'),
    # path('test-result/', views.TestResults.as_view(), name='TestResult'),
    # path('course/<int:pk>/chat', views.ViewChat, name="ViewChat"),
    # path('course/chat/add/', views.AddComment, name="AddComment"),
    path('ckeditor', include('ckeditor_uploader.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

edusystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('eduapp.urls', 'eduapp') , namespace='edu-app')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eduapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from .models import AppUser
# , Course, CourseContent, HomeWork
from ckeditor.widgets import CKEditorWidget

User = get_user_model()

# class RegistrationForm(forms.ModelForm):
#     confirm_password = forms.CharField(widget = forms.PasswordInput)
#     password = forms.CharField(widget = forms.PasswordInput)
#     avatar = forms.FileField(required=False)
#     email = forms.EmailField(required=False)
#     CHOICES = (
#         ('teacher', 'Оқытушы'),
#         ('student', 'Оқушы'),
#     )
#     type = forms.ChoiceField(required=True, choices = CHOICES)

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['username'].help_text = "Атыңыз"
#         self.fields['username'].label = 'Логин'
#         self.fields['username'].help_text = "Міндетті. Логин 150 таңба немесе одан аз болуы. Тек әріптер, цифрлар ғана болуы керек."
#         self.fields['password'].label = 'Құпия сөз'
#         self.fields['confirm_password'].label = 'Құпия сөзді қайталаңыз'
#         self.fields['first_name'].label = 'Фамилия'
#         self.fields['last_name'].label = 'Аты'
#         self.fields['email'].label = 'email'
#         self.fields['avatar'].label = 'Аватар'
#         self.fields['type'].label = 'Қолданушы түрін таңдаңыз'

    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     if User.objects.filter(email=email).exists():
    #         raise forms.ValidationError('Бұл почта жүйеде тіркелген',code='invalid')
    #     return email
    # def clean_username(self):
    #     username = self.cleaned_data['username']
    #     if User.objects.filter(username=username).exists():
    #         raise forms.ValidationError('Бұл логин жүйеде тіркелген',code='invalid')
    #     return username
    # class Meta:
    #     model = User
    #     fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'email', 'avatar', 'type']
        

class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'user'
        self.fields['username'].help_text = ''
        self.fields['password'].label = 'password'
    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(username + " - not found")
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("wrong password")
        return self.cleaned_data

# class CourseCreateForm(forms.ModelForm):
#     description = forms.CharField(widget=CKEditorWidget(),label="Сипаттамасы")
#     aim = forms.CharField(widget=CKEditorWidget(),label="Мақсаты")
#     class Meta:
#         model = Course
#         fields = ['category', 'title','aim', 'description','cover']

# class CourseContentCreateForm(forms.ModelForm):
#     text = forms.CharField(widget=CKEditorWidget(),label="Текст")
#     homework = forms.CharField(widget=CKEditorWidget(),label="Үй тапсырмасы")
#     class Meta:
#         model = CourseContent
#         fields = ['priority', 'title', 'video' ,'text','document', 'homework']

# class HomeWorkForm(forms.ModelForm):
#     class Meta:
#         model = HomeWork
#         fields = ['title', 'file']

eduapp/views.py
from django.views.generic import DetailView, View
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.core.mail import mail_admins, send_mail,EmailMessage
from django.core.files.storage import FileSystemStorage
import datetime
from django.contrib.auth import authenticate, login, logout
from django.views.generic.edit import UpdateView, DeleteView 
from .forms import LoginForm
# , CourseCreateForm, CourseContentCreateForm, HomeWorkForm,  RegistrationForm
from django.urls import reverse_lazy
import pandas as pd
import random

from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from rest_framework import status

class MainPage(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.add_message(request, messages.INFO, 'Please, log in')
            return HttpResponseRedirect('/')
        category = Category.objects.all()
        user = request.user
        last_courses = Course.objects.all().order_by('-pk')[:4]
        template = 'eduapp/main-student.html'
        if user.is_authenticated:
            if user.is_superuser:
                logout(request)
                messages.add_message(request, messages.INFO, 'Please, log in')
                return HttpResponseRedirect('/')
            print(user)
            context = {
                'categories':category,
                'lastcourses':last_courses
            }
            return render(request, template, context)

# class RegistrationView(View):
#     def get(self, request, *args, **kwargs):
#         form = RegistrationForm(request.POST or None)
#         context = {
#             'form': form,
#         }
#         return render(request, 'eduapp/signup.html', context)

#     def post(self, request, *args, **kwargs):
#         form = RegistrationForm(request.POST,request.FILES or None)
#         if form.is_valid():
#             new_user = form.save(commit=False)
#             new_user.username = form.cleaned_data['username']
#             new_user.email = form.cleaned_data['email']
#             new_user.first_name = form.cleaned_data['first_name']
#             new_user.last_name = form.cleaned_data['last_name']
#             new_user.save()
#             new_user.set_password(form.cleaned_data['password'])
#             new_user.save()
#             AppUser.objects.create(
#                 user=new_user,
#                 avatar=request.FILES['avatar'],
#                 type=form.cleaned_data['type']
#             )
#             user = authenticate(
#                 username=new_user.username, password=form.cleaned_data['password']
#             )
#             login(request, user)
#             messages.add_message(request, messages.SUCCESS, 'Жүйеге сәтті тіркелдіңіз')
#             return HttpResponseRedirect('/')
#         else:
#             print(form.errors)
#         context = {
#             'form': form,
#         }
#         return render(request, 'eduapp/signup.html', context)

class LoginView(View):
    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        context = {
            'form': form,
        }
        user = request.user
        if user.is_authenticated:
            return HttpResponseRedirect('/main')
        return render(request, 'eduapp/login.html', context)

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(
                username=username, password=password
            )
            if user:
                login(request, user)
                print(user)
                return HttpResponseRedirect('/main')
        context = {
            'form': form,
        }
        return render(request, 'eduapp/login.html', context)

class Search(View):
    def post(self, request, *args, **kwargs):
        quy= request.POST.get("quy")
        list = CourseContent.objects.filter(title__icontains=quy)
        context = {
            'list':list
        }
        return render(request, 'eduapp/search_res.html', context)
# class CreateCourse(View):
#     def get(self, request, *args, **kwargs):
#         form = CourseCreateForm(request.POST or None)
#         context = {
#             'form': form,
#         }
#         return render(request, 'eduapp/create-course.html', context)
#     def post(self, request, *args, **kwargs):
#         form = CourseCreateForm(request.POST,request.FILES or None)
#         user = AppUser.objects.get(user=request.user)
#         if form.is_valid():
#             new_course = form.save(commit=False)
#             new_course.creator = user
#             new_course.save()
#         context = {
#             'form': form,
#         }
#         messages.add_message(request, messages.SUCCESS, 'Жаңа курс жүйеге сәтті қосылды')
#         return HttpResponseRedirect('/')

# class TeachersCourse(View):
#     def get(self, request, *args, **kwargs):
#         user = AppUser.objects.get(user=request.user)
#         courses = Course.objects.filter(creator=user)
#         context = {
#             'courses': courses,
#         }
#         return render(request, 'eduapp/teacher-course.html', context)

class StudentsCourse(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.add_message(request, messages.INFO, 'Please, log in')
            return HttpResponseRedirect('/')
        user = AppUser.objects.get(user=request.user)
        
        print(AdmissionCourse.objects.filter(owner=user).first())
        courses = AdmissionCourse.objects.filter(owner=user).first()
        admission = 'asdsda'
        context = {
            'courses': courses,
        }
        return render(request, 'eduapp/student-course.html', context)

# class TeachersCourseDetail(View):
#     def get(self, request, *args, **kwargs):
#         form = CourseContentCreateForm()
#         user = AppUser.objects.get(user=request.user)
#         course_pk = kwargs.get('pk')
#         course = Course.objects.get(creator=user, pk = course_pk)
#         child_courses = CourseContent.objects.filter(course=course).order_by('-priority').reverse()
#         tests = ParentTest.objects.filter(course = course)
#         results = TestResult.objects.filter(test__course=course)  
#         context = {
#             'course': course,
#             'form':form,
#             'courses':child_courses,
#             'tests':tests,
#             'results':results
#         }
#         return render(request, 'eduapp/teacher-course-detail.html', context)

    # def post(self, request, *args, **kwargs):
    #     form = CourseContentCreateForm(request.POST,request.FILES or None)
    #     user = AppUser.objects.get(user=request.user)
    #     course_pk = kwargs.get('pk')
    #     course = Course.objects.get(creator=user, pk = course_pk)
    #     if form.is_valid():
    #         new_course_content = form.save(commit=False)
    #         new_course_content.course=course
    #         new_course_content.save()
    #         course_chat = Chat.objects.create(
    #             course = new_course_content
    #         )
    #     context = {
    #         'course': course,
    #         'form':form
    #     }
    #     messages.add_message(request, messages.SUCCESS, 'Жаңа сабақ жүйеге сәтті қосылды')
    #     return HttpResponseRedirect('/course-list/'+str(course_pk)+'/')

# @csrf_exempt
# def ViewChat(request,pk):
#     if request.method == "GET":
#         course = CourseContent.objects.get(pk=pk)
#         chat = Chat.objects.get(course=course)
#         chat_id = chat.pk
#         messages = Message.objects.filter(chat=chat)
#         chat = ChatSerializer(messages, many=True)
#         data = {
#             'data':chat.data,
#             'chat':chat_id
#         }
#         return JsonResponse(data, safe=True)
#     if request.method == 'POST':
#         print('pp')
# @csrf_exempt
# def AddComment(request):
#     if request.method == 'POST':
#         data = JSONParser().parse(request)
#         chat = data['chat']
#         message = data['message']
#         user = AppUser.objects.get(user=request.user)
#         comment_chat = Chat.objects.get(pk=chat)
#         mes = Message.objects.create(
#             chat = comment_chat,
#             user = user,
#             message = message
#         )
#         if mes:
#             return JsonResponse(data, status=200)

# class CourseContentUpdate(UpdateView):
#     model = CourseContent 
#     fields = [ 
#         "title", 
#         "text",
#         "document",
#         'video',
#         'homework',
#         'priority'
#     ]
#     def get_success_url(self):
#         return reverse_lazy('edu-app:TeachersCourseDetail', kwargs={'pk': self.object.course.pk})
# class CourseContentDelete(DeleteView):
#     model = CourseContent

#     def get_success_url(self):
#         return reverse_lazy('edu-app:TeachersCourseDetail', kwargs={'pk': self.object.course.pk})
class CourseDetail(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.add_message(request, messages.INFO, 'Please, log in')
            return HttpResponseRedirect('/signin/')
        user = AppUser.objects.get(user=request.user)
        course_pk = kwargs.get('pk')
        course = CourseContent.objects.get( pk = course_pk)
      
        context = {
            'course': course,
            'site-user':user,
        }
        return render(request, 'eduapp/course-content-detail.html', context)

eduapp/templates/eduapp/course-by-category.html
{% extends 'eduapp/main-template.html' %}
{% block title %}
Spaces
{% endblock %}
{% block content %}
<p class="uk-text-lead uk-margin-bottom">
    {{category}}
</p>
<div class="uk-grid-match uk-child-width-1-3@s uk-text-center" uk-grid>
    {% for course in courses %}
    <a class="uk-link-heading" href="{% url 'edu-app:CourseShow' course.pk %}">
        <div class="uk-card uk-card-default uk-card-hover">
            <div class="uk-card-badge uk-label">
                {{course.category}}
            </div>
            <div class="uk-card-media-top">
                <div class="uk-background-cover uk-height-small uk-panel uk-flex uk-flex-center uk-flex-middle" style="background-image: url({{course.cover.url}});">
                </div>
            </div>
            <div class="uk-card-body">
                <h3 class="uk-card-title">
                    {{course.title}}
                </h3>
            </div>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}

eduapp/templates/eduapp/course-content-detail.html
{% extends 'eduapp/main-template.html' %}
{% load crispy_forms_tags %}
{% block title %}
content
{% endblock %}
{% block content %}
{% if course %}
<span class="uk-badge uk-margin-bottom">
    {{course.course.title}}
</span>
<h2 class="uk-h2 uk-margin-remove-top">
    {{course.title}}
</h2>
{%if course.video%}
<hr class="uk-divider-icon">
<video src="{{course.video.url}}" controls playsinlineuk-video></video>
{%endif%}

<hr class="uk-divider-icon">
<div class="ckeditor-text">
    {{course.text|safe}}
</div>
{% if course.homework%}
<div class="ckeditor-text">
    {{course.text|safe}}
</div>
{%endif%}
{% if course.document %}
<span class="uk-white-text">
    Attached file:
</span>
<a href="{{course.document.url}}" download>
    {{course.document}}
</a>
{% endif %}
<hr class="uk-divider-icon">
{% endif %}
{% endblock %}

eduapp/templates/eduapp/coursecontent_confirm_delete.html
{% extends 'eduapp/main-template.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Сабақты Өшіру
{% endblock %}
{% block content %}
        <form method="post">{% csrf_token %} 
            <div class="uk-alert-danger" uk-alert>
                <p>Келесі сабақ - "{{ object }}" жүйеден өшіріледі</p>
            </div>
            <div class="uk-text-right">
                <input class="uk-button uk-button-primary uk-margin-small-top" type="submit" value="Өшіру">
            </div> 
        </form>
{% endblock %}

eduapp/templates/eduapp/coursecontent_form.html
{% extends 'eduapp/main-template.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Сабақты Өзгерту
{% endblock %}
{% block content %}
    {% if form %}
        <form class="form edu-form" method="post" class="uk-form-width-large" enctype="multipart/form-data"> 
            {% csrf_token %}
            {{form|crispy|safe}}
            {{form.media}}
            <button class="uk-button uk-margin-small-top uk-button-primary" type="submit">
                Өзгерту
            </button>
        </form>
    {% endif %}
{% endblock %}

eduapp/templates/eduapp/login.html
{% extends 'eduapp/main-template.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
log in
{% endblock %}
{% block content %}
<div uk-grid class="login-container">
    <div class="uk-width-expand">
        <div class="uk-inline uk-dark">
            <img src="{% static 'eduapp/img/1.jpg' %}">

        </div>
    </div>
    <div class="uk-width-2-5@m">
        <div class="uk-flex uk-flex-column uk-flex-center uk-height-1-1">
            <form class="form" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="uk-button uk-button-primary uk-margin-small-top " type="submit">
                    Log in</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

eduapp/templates/eduapp/main-template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'books/images/ico.ico'%}" sizes="32x32" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'eduapp/css/uikit.min.css' %}" />
    <link rel="stylesheet" href="{% static 'eduapp/css/custom.css'%}">
    <script src="{% static 'eduapp/js/jquery.js' %}"></script>
    <script src="{% static 'eduapp/js/uikit.min.js' %}"></script>
    <script src="{% static 'eduapp/js/uikit-icons.min.js' %}"></script>
    <script src="{% static 'eduapp/js/vue.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>


</head>

<body class="">
    <header>
        <div uk-sticky="media: 960" class="uk-navbar-container tm-navbar-container uk-navbar-white uk-background-primary uk-navbar-transparent uk-sticky uk-sticky-fixed uk-active uk-sticky-below">
            <div class="uk-container uk-container-expand">
                <nav class="uk-navbar">
                    <div class="uk-navbar-left">
                        {% if user.username %}
                        <a href="/main" class="uk-navbar-item uk-logo">
                            SOC Knowledge base
                        </a>
                        {%else%}
                        <a href="/" class="uk-navbar-item uk-logo">
                            SOC Knowledge base
                        </a>
                        {%endif%}
                    </div>
                    <div class="uk-navbar-right">
                        <ul class="uk-navbar-nav uk-visible@m">
                            {% if user.username %}
                            {% if user.aps.type == 'student' %}
                            <li>
                                <a class="" href="{% url 'edu-app:StudentsCourse' %}">
                                    Read list
                                </a>
                            </li>
                            <li class="uk-text-center">
                                <a class="" href="#my-search" type="button">
                                    <span uk-icon="search"></span>
                                </a>
                                <div uk-dropdown="mode: click">
                                    <form class="uk-search uk-width-1-2 uk-search-default" method="POST" action="{% url 'edu-app:SearchPage' %}">
                                        {% csrf_token %}

                                        <input class="uk-search-input uk-text-emphasis" type="text" placeholder="Search" name="quy">
                                    </form>
                                </div>
                            </li>
                            {% endif %}
                            <li>
                                <a class="" title="{{user.username}}">
                                    <span class="avatar uk-background-cover uk-flex uk-flex-center uk-flex-middle" style="background-image: url({{user.aps.avatar.url}});">
                                    </span>
                                    {{user.get_full_name}}
                                </a>
                            </li>
                            <li>
                                <a class="" href="{% url 'edu-app:LogOut' %}">
                                    <span uk-icon="sign-out"></span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                        <a uk-navbar-toggle-icon="" href="#offcanvas-slide" uk-toggle="" class="uk-navbar-toggle uk-hidden@m uk-icon uk-navbar-toggle-icon" aria-expanded="false">
                        </a>
                    </div>
                </nav>
            </div>
        </div>
        <div id="offcanvas-slide" uk-offcanvas>
            <div class="uk-offcanvas-bar">
                <ul class="uk-nav uk-nav-default">
                    {% if user.username %}
                    <li>
                        <a class="uk-text-center" title="{{user.username}}">
                            <span class="avatar uk-background-cover uk-flex uk-flex-center uk-flex-middle uk-margin-auto-left uk-margin-auto-right " style="background-image: url({{user.aps.avatar.url}});">
                            </span>
                            <h4 class="uk-text-capitalize uk-margin-small-top">
                                {{user.get_full_name}}
                            </h4>
                        </a>
                    </li>
                    {% if user.aps.type == 'student' %}
                    <li class="uk-text-center">
                        <a class="" href="{% url 'edu-app:StudentsCourse' %}">
                            Read list
                        </a>
                    </li>
                    <li class="uk-text-center">
                        <a class="" href="#my-search" uk-toggle>
                            <span uk-icon="search"></span>
                        </a>
                    </li>

                    {% endif %}
                    <li class="uk-text-center">
                        <a class="" href="{% url 'edu-app:LogOut' %}">
                            <span uk-icon="sign-out"></span>
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a title="Жүйеге кіру" href="{% url 'edu-app:SignIn' %}">
                            <span uk-icon="sign-in"></span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>

    <main class="">
        <div class="uk-container uk-margin-large-top">
            {% if messages %}
            {% for message in messages %}
            <script>
                UIkit.notification("{{ message }}", { status: '{{ message.tags }}' })
            </script>
            {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer class="main-back-1">
        <div class="uk-container uk-margin-large-top">
            За #ИБэ!
        </div>
    </footer>
</body>

</html>

eduapp/templates/eduapp/main.html
{% extends 'eduapp/main-template.html' %}
{% block title %}
    Сайт блогы
{% endblock %}
{% block content %}
<div uk-grid>
    <div class="uk-width-expand@m">
        <p class="uk-text-lead uk-margin-bottom">
            Менің курстарым
        </p>
        <div class="uk-grid-match uk-child-width-1-3@s uk-text-center" uk-grid>
            {% for course in lastcourses %}
                <a  class="uk-link-heading" href="{% url 'edu-app:TeachersCourseDetail' course.pk %}">
                    <div class="uk-card uk-card-default uk-card-hover">
                        <div class="uk-card-badge uk-label">
                            {{course.category}}
                        </div>
                        <div class="uk-card-media-top">
                            <div class="uk-background-cover uk-height-small uk-panel uk-flex uk-flex-center uk-flex-middle" style="background-image: url({{course.cover.url}});">
                            </div>
                        </div>
                        <div class="uk-card-body">
                            <h3 class="uk-card-title">
                                {{course.title}}
                            </h3>
                            <div>
                                {{course.aim|safe}}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

eduapp/templates/eduapp/search_res.html
{% extends 'eduapp/main-template.html' %}
{% load crispy_forms_tags %}
{% block title %}
Search
{% endblock %}
{% block content %}


<ul class="uk-list uk-list-decimal">
    {% if list %}
    {% for course in list %}
    <li>
        <a href="{% url 'edu-app:CourseDetail' course.pk %}" class="">
            {{course.title}}
        </a>
    </li>
    {% endfor %}
    {% else %}
    not result
    {% endif %}

</ul>

{% endblock %}

eduapp/templates/eduapp/student-course-detail.html
{% extends 'eduapp/main-template.html' %}
{% load crispy_forms_tags %}
{% block title %}
Spaces
{% endblock %}
{% block content %}
{% if course %}

<div>
    <h2 class="uk-h2">
        {{course.title}}
    </h2>

</div>
<div class="detail-blur-p  uk-background-cover uk-light uk-height-medium uk-panel uk-flex uk-flex-center uk-flex-middle" style="background-image: url({{course.cover.url}});">
</div>

<div uk-grid>
    <div class="uk-width-1-4@s">
        <ul class="uk-list">
            <h4 class="uk-h4 uk-margin-small-top">
                Content list
            </h4>
            {% for course in courses %}
            <li>
                <a href="{% url 'edu-app:CourseDetail' course.pk %}" class="">
                    {{course.priority}}.
                    {{course.title}}
                </a>
            </li>
            {% endfor %}
        </ul>
        <!-- {% if admission == False %}
        <ul class="uk-list">
            <h4 class="uk-h4 uk-margin-small-top">
                Бақылау тесті тізімі
            </h4>
            {% for test in tests %}
            <li>
                <a href="{% url 'edu-app:PastTest' test.pk %}" class="">
                    {{ forloop.counter }}.{{test.title}}
                </a>
            </li>
            {% endfor %}
        </ul>
        {% endif %} -->
    </div>
    <div class="uk-width-expand">
        <div class="uk-child-width-1-1@s" uk-grid>
            <div>
                <div class="uk-panel uk-panel-box uk-margin-small-top">
                    <div class="ckeditor-text">
                        {{course.description|safe}}
                    </div>
                    {%if course.aim%}
                    <div class="ckeditor-text">
                        {{course.aim|safe}}
                    </div>
                    {% endif %}
                </div>
                {% if admission == True %}
                <a href="{% url 'edu-app:CourseAdd' course.pk %}" class="uk-text-right uk-button uk-button-primary">
                    Read later
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}